### ISSUE TITLE
emmm...

### ISSUE THREAD

**Issue by alphazhugit** [iamxym/Deep-Fourier-based-Arbitrary-scale-Super-resolution-for-Real-time-Rendering#1]
Is the current code able to run normally?

**Comment by iamxym** [comment]
We uploaded the code of network, training and dataloader in this project except the dataset. 
What problem do you have? Can you provide more details?

**Comment by alphazhugit** [comment]
> We uploaded the code of network, training and dataloader in this project except the dataset.我们上传了本项目中除数据集之外的网络、训练和数据加载器的代码。 What problem do you have? Can you provide more details?你有什么问题？中方能否介绍更多详情？

Thank you very much for your reply. Perhaps I was hoping to have a demo to test, but currently there is no relevant guidance, such as an installation guide like other projects have. Perhaps you will release something like that in the future?

**Comment by iamxym** [comment]
We are glad to release our work totally including the weight file of pretrained model for testing. But the test data are generated by the modified version of unreal engine and script code for preprocess. I think we need more time to prepare them.
