### ISSUE TITLE
Add example how to use this code

### ISSUE THREAD

**Issue by pablospe** [iamxym/Deep-Fourier-based-Arbitrary-scale-Super-resolution-for-Real-time-Rendering#2]
It would be nice to have little instructions on how to run the code. Perhaps with a small dataset example. Also, the dependency installation instructions.

**Comment by iamxym** [comment]
Sure! We are glad to give the instruction, the weight file of pre-trained newwork model and frame example for inference. However, the test data are generated by the modified version of unreal engine and script code for preprocess. Also, we are too busy to deal with these things carefully. I think we need more time to prepare them.
